# Flask
DEBUG = True
PORT = 5000
HOST = "192.168.237.13"
SECRET_KEY = "a1841b5ef57d8de68b17203721a8b094f05e1e319bf23aeb"

# JWT (https://pythonhosted.org/Flask-JWT/)
JWT_VERIFY_EXPIRATION = False

# SQLAlchemy
SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = True

# MYSQL - TROCAR NOMES
DB_HOST = "localhost"
DB_SCHEMA = "dacomDoor"
DB_USERNAME = "user"
DB_PASSWORD = "user"

# MySQL + SQLAlchemy
SQLALCHEMY_DATABASE_URI = (
	"mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_ADDR}/{DB_NAME}"
	.format(
		DB_USER=DB_USERNAME,
		DB_PASS=DB_PASSWORD,
		DB_ADDR=DB_HOST,
		DB_NAME=DB_SCHEMA
	)
)
