"""empty message

Revision ID: 5bbc5286097d
Revises: 4da87715226f
Create Date: 2019-11-28 13:45:46.515175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bbc5286097d'
down_revision = '4da87715226f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'eventType',
               existing_type=mysql.ENUM('IN', 'OUT', 'DOOR_OPENED'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'eventType',
               existing_type=mysql.ENUM('IN', 'OUT'),
               nullable=True)
    # ### end Alembic commands ###
